Repository RollingPaperTeam/rolling-papaer-web, pull requests merged in 2023-12, with the labels that each got.

#18 [feat] 글로벌 스타일 추가
  rolling-papaer/src/Main.js
Labels: enhancement

#15 [CREATE] card component
  rolling-papaer/src/components/badge/RelationBadge.jsx
  rolling-papaer/src/components/card/Card.jsx
  rolling-papaer/src/components/card/CardContent.jsx
  rolling-papaer/src/components/card/CardFooter.jsx
  rolling-papaer/src/components/card/CardProfile.jsx
  rolling-papaer/src/components/card/CardProfileName.jsx
  rolling-papaer/src/components/card/CardProvider.jsx
  rolling-papaer/src/components/card/CardRelationBadge.jsx
  rolling-papaer/src/utils/timeformatUtil.js
Labels: enhancement

#19 [CREATE] Button 컴포넌트 구현
  rolling-papaer/src/components/button/Button.jsx
  rolling-papaer/src/components/button/ButtonStyle.jsx
  rolling-papaer/src/static/add.svg
  rolling-papaer/src/static/arrow_down.svg
  rolling-papaer/src/static/arrow_next.svg
  rolling-papaer/src/static/arrow_prev.svg
  rolling-papaer/src/static/check.svg
  rolling-papaer/src/static/deleted.svg
  rolling-papaer/src/static/edit.svg
  rolling-papaer/src/static/plus.svg
  rolling-papaer/src/static/share.svg
Labels: enhancement

#26 create 고성선 cardlist 컴포넌트 구현
  rolling-papaer/src/api/Routes.js
  rolling-papaer/src/components/button/NextButton.js
  rolling-papaer/src/components/card/CardBox.js
  rolling-papaer/src/components/card/CardList.jsx
  rolling-papaer/src/components/card/RecentProfile.jsx
  rolling-papaer/src/components/card/translateValue.js
  rolling-papaer/src/pages/rolling-paper-page/CardSection.jsx
  rolling-papaer/src/pages/rolling-paper-page/RollingPaperListPage.jsx
  rolling-papaer/src/static/bg-beige.png
  rolling-papaer/src/static/bg-blue.png
  rolling-papaer/src/static/bg-green.png
  rolling-papaer/src/static/bg-purple.png
  rolling-papaer/src/static/mock-recipient-list.json
Labels: enhancement

#20 [CREATE] post page secondary header 구현
  rolling-papaer/src/components/header/PostHeader/PostHeader.jsx
  rolling-papaer/src/components/header/PostHeader/PostHeaderItems.jsx
  rolling-papaer/src/components/header/PostHeader/PostHeaderProvider.jsx
Labels: enhancement

#34 Day7 고성선 32 create list페이지 카드 이전 다음 버튼
  rolling-papaer/src/components/button/Button.jsx
  rolling-papaer/src/components/button/ButtonStyle.jsx
  rolling-papaer/src/components/button/NextButton.js
  rolling-papaer/src/components/button/NextButton.jsx
  rolling-papaer/src/components/button/PrevButton.jsx
  rolling-papaer/src/pages/rolling-paper-page/CardSection.jsx
Labels: enhancement

#30 Day6 이나경 21 emoji badge 및 emoji badge list구현
  rolling-papaer/src/components/badge/EmojiBadge.jsx
  rolling-papaer/src/components/badge/EmojiBadgeList.jsx
  rolling-papaer/src/test/EmojiBadgeListTest.jsx
Labels: enhancement

#38 Day7 김미진 33 Button 컴포넌트 오류 수정
  rolling-papaer/src/components/button/Button.jsx
  rolling-papaer/src/components/button/ButtonStyle.jsx
  rolling-papaer/src/static/add_20_disabled.svg
  rolling-papaer/src/static/add_disabled.svg
  rolling-papaer/src/static/deleted_disabled.svg
Labels: enhancement

#39 Day6 고성선 27 main header 컴포넌트 추가
  rolling-papaer/public/index.html
  rolling-papaer/src/App.js
  rolling-papaer/src/Main.js
  rolling-papaer/src/components/header/Header.jsx
  rolling-papaer/src/components/header/Nav.jsx
  rolling-papaer/src/pages/rolling-paper-page/RollingPaperListPage.jsx
  rolling-papaer/src/static/Logo.png
Labels: enhancement

#47 Day7 이나경 43 fix postheader 좌우 padding
  rolling-papaer/src/components/header/PostHeader/PostHeader.jsx
  rolling-papaer/src/components/header/PostHeader/PostHeaderItems.jsx
  rolling-papaer/src/components/header/PostHeader/PostHeaderProvider.jsx
Labels: bug

#52 Day7 고성선 42 create rollingpaperpage 메인 페이지
  rolling-papaer/src/pages/Main.jsx
  rolling-papaer/src/pages/MainPage.jsx
  rolling-papaer/src/static/content1.png
  rolling-papaer/src/static/content2.png
Labels: enhancement

#70 Hot fix 헤더 백그라운드 컬러 지정
  rolling-papaer/src/components/header/Nav.jsx
Labels: bug

#55 Day7 이나경 36 emoji 추가 버튼 구현
  rolling-papaer/package-lock.json
  rolling-papaer/package.json
  rolling-papaer/src/components/button/EmojiPickerButton.jsx
Labels: enhancement

#58 Day8 고성선 57 메인 페이지 list 페이지 구경해보기 버튼 구현
  rolling-papaer/src/api/Routes.js
  rolling-papaer/src/api/api.js
  rolling-papaer/src/components/button/LinkButton.jsx
  rolling-papaer/src/components/card/CardList.jsx
  rolling-papaer/src/pages/Main.jsx
  rolling-papaer/src/pages/MainPage.jsx
  rolling-papaer/src/pages/rolling-paper-page/CardSection.jsx
  rolling-papaer/src/pages/rolling-paper-page/RollingPaperListPage.jsx
Labels: enhancement

#60 [feat] cardlist에 emoji badgeList 추가
  rolling-papaer/src/components/card/CardList.jsx
Labels: enhancement

#65 Day8 김미진 64 Option 컴포넌트 구현
  rolling-papaer/src/components/option/Option.jsx
  rolling-papaer/src/static/current_color.svg
  rolling-papaer/src/static/person.svg
Labels: enhancement

#72 [fix] 카드 이미지 변형되는 부분 cover로 변경
  rolling-papaer/src/components/card/CardBox.js
Labels: bug

#68 Day8 김미진 29 post(color, image case) 페이지 구현
  rolling-papaer/src/pages/post-color-image-case-page/ColorImageCasePage.jsx
  rolling-papaer/src/static/house.jpg
  rolling-papaer/src/static/rudolf.png
  rolling-papaer/src/static/santa.jpg
  rolling-papaer/src/static/snowman.jpg
Labels: enhancement

#67 Day8 김미진 66 Text Field 컴포넌트 구현
  rolling-papaer/src/components/textfield/TextEditor.jsx
  rolling-papaer/src/components/textfield/TextField.jsx
  rolling-papaer/src/static/arrow_open.svg
Labels: enhancement

#63 [feat] list 페이지 Card 리스트 Link화
  rolling-papaer/src/Main.js
  rolling-papaer/src/components/card/CardList.jsx
Labels: enhancement

#78 [CREATE] postid 페이지 구현
  rolling-papaer/src/App.js
  rolling-papaer/src/api/apis.js
  rolling-papaer/src/components/header/PostHeader/PostHeader.jsx
  rolling-papaer/src/containers/CardLazyGridContainer.jsx
  rolling-papaer/src/pages/rolling-paper-page/RolingPaperPage.jsx
  rolling-papaer/src/static/loading.svg
  rolling-papaer/src/static/mock-recipient-results.json
  rolling-papaer/src/static/mock-recipient.json
Labels: enhancement

#80 [CREATE] Day9 이나경 79 네트워크 통신 custom hook 구현
  rolling-papaer/src/containers/CardLazyGridContainer.jsx
  rolling-papaer/src/hooks/NetworkHook.jsx
Labels: enhancement

#85 Day9 고성선 77 main page 반응형 추가 모바일 테블릿
  rolling-papaer/src/components/button/LinkButton.jsx
  rolling-papaer/src/components/button/PostLinkButton.jsx
  rolling-papaer/src/components/header/Nav.jsx
  rolling-papaer/src/pages/Main.jsx
  rolling-papaer/src/pages/MainPage.jsx
  rolling-papaer/src/theme/mediaQuery.js
Labels: enhancement

#87 Day10 김미진 48 post message 페이지 구현
  rolling-papaer/package-lock.json
  rolling-papaer/package.json
  rolling-papaer/src/pages/post-message-page/PostMessagePage.jsx
  rolling-papaer/src/static/img.jpg
Labels: enhancement

#90 [CREATE] Day10 이나경 83 신규 message 추가 UI 구현
  rolling-papaer/src/components/button/Button.jsx
  rolling-papaer/src/components/card/Card.jsx
Labels: enhancement

#92 Day10 김미진 88 Modal 컴포넌트 구현
  rolling-papaer/src/components/modal/Modal.jsx
Labels: enhancement

#101 [CREATE] Day10 이나경 95 card onclick 연결
  rolling-papaer/src/Main.js
  rolling-papaer/src/components/card/Card.jsx
  rolling-papaer/src/components/card/CardProvider.jsx
  rolling-papaer/src/components/modal/Modal.jsx
  rolling-papaer/src/containers/CardLazyGridContainer.jsx
Labels: enhancement

#100 Day9 고성선 86 link page 반응형 및 헤더 bg 마진부분 이슈
  rolling-papaer/src/components/badge/EmojiBadge.jsx
  rolling-papaer/src/components/badge/EmojiBadgeList.jsx
  rolling-papaer/src/components/button/LinkButton.jsx
  rolling-papaer/src/components/button/NextButton.jsx
  rolling-papaer/src/components/button/PrevButton.jsx
  rolling-papaer/src/components/card/CardBox.js
  rolling-papaer/src/components/card/CardList.jsx
  rolling-papaer/src/components/header/Nav.jsx
  rolling-papaer/src/pages/rolling-paper-page/CardSection.jsx
Labels: bug, enhancement

#98 Day10 김미진 93 작성한 인원 수 count 컴포넌트 구현
  rolling-papaer/src/components/card/CardList.jsx
  rolling-papaer/src/components/card/CountPerson.jsx
Labels: enhancement

#113 Day11 김미진 99 프로필 이미지 리스트
  rolling-papaer/package-lock.json
  rolling-papaer/package.json
  rolling-papaer/src/components/card/Card.jsx
  rolling-papaer/src/components/card/CardProfileImg.jsx
  rolling-papaer/src/pages/post-message-page/PostMessagePage.jsx
Labels: enhancement

#126 [feat] post page grid 반응형 , modal mobile 사이즈 적용
  rolling-papaer/src/components/modal/Modal.jsx
  rolling-papaer/src/containers/CardLazyGridContainer.jsx
Labels: enhancement

#135 잘못된 페이지 경로 수정
  rolling-papaer/src/Main.js
  rolling-papaer/src/pages/post-message-page/PostMessagePage.jsx
Labels: bug

#146 Last dance 이나경 145 postid emojilist 등장사라짐 애니메이션
  rolling-papaer/src/components/header/PostHeader/HeaderEmojiList.jsx
  rolling-papaer/src/components/header/PostHeader/PostHeader.jsx
Labels: documentation, enhancement
